[package]
name = "chat"
version = "0.1.0"
authors = ["Christian Petersen <humanoidism@gmail.com>"]

[dependencies]
http-muncher = "0.2.0"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"

[dependencies.mio]
git = "https://github.com/carllerche/mio"

